#!/usr/bin/env bash

# setting up EndeavourOS repo:
# try fix keyring issue 1.1.2024
cd /
pacman-key --init && pacman -Syu --noconfirm && pacman -Syu base-devel --noconfirm
pacman -Sy --noconfirm --needed archlinux-keyring wget
wget https://raw.githubusercontent.com/endeavouros-team/EndeavourOS-ISO/plasma6/airootfs/etc/pacman.conf
cp pacman.conf /etc/pacman.conf
wget https://raw.githubusercontent.com/endeavouros-team/PKGBUILDS/master/endeavouros-mirrorlist/endeavouros-mirrorlist
cp endeavouros-mirrorlist /etc/pacman.d/endeavouros-mirrorlist
pacman-key --recv-key 0F20FADC599D1C46EB556455AED8858E4B9813F1 --keyserver keyserver.ubuntu.com && pacman-key --lsign-key 0F20FADC599D1C46EB556455AED8858E4B9813F1
pacman-key --init
pacman -Syy --noconfirm endeavouros-keyring 
pacman -S --noconfirm endeavouros-mirrorlist
pacman -S --noconfirm reflector 
reflector --age 2 --number 23 --save /etc/pacman.d/mirrorlist
