#!/usr/bin/env bash

echo "### start building calamares git package"
echo "%wheel         ALL = (ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers
pacman -Syu
pacman -S --noconfirm --needed git cmake extra-cmake-modules python-jsonschema python-pyaml python-unidecode gawk qt6-svg qt6-webengine yaml-cpp networkmanager upower kcoreaddons kconfig ki18n kservice kwidgetsaddons  squashfs-tools rsync pybind11 cryptsetup doxygen dmidecode gptfdisk hwinfo kparts polkit-qt6 python solid qt6-tools libpwquality ckbcomp qt6-declarative
#wget -qN --show-progress -P "/tmp/" "https://archive.archlinux.org/packages/k/kpmcore/kpmcore-24.05.2-1-x86_64.pkg.tar.zst"
#pacman -U --noconfirm "/tmp/kpmcore-24.05.2-1-x86_64.pkg.tar.zst"
useradd -m -G wheel -s /bin/bash build
cd /home/build
mkdir -p /home/build/packages
chown -R build:build /home/build/packages
# building latest calamares git version
mkdir /home/build/calamares-git
chown -R build:build /home/build/calamares-git
cd /home/build/calamares-git
sudo -u build wget https://raw.githubusercontent.com/endeavouros-team/PKGBUILDS/master/calamares-git/PKGBUILD
sudo -u  build makepkg -f
cp *.pkg.tar.zst /home/build/packages/
rm -R /home/build/calamares-git
echo "### end building calamares-git"
