#!/usr/bin/env bash

# building calamares git packages:
echo "%wheel         ALL = (ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers
pacman -Syu
pacman -S --noconfirm --needed git cmake extra-cmake-modules python-jsonschema python-pyaml python-unidecode gawk qt6-svg qt6-webengine yaml-cpp networkmanager upower kcoreaddons kconfig ki18n kservice kwidgetsaddons kpmcore squashfs-tools rsync pybind11 cryptsetup doxygen dmidecode gptfdisk hwinfo kparts polkit-qt6 python solid qt6-tools libpwquality ckbcomp qt6-declarative
useradd -m -G wheel -s /bin/bash build
cd /home/build
mkdir -p /home/build/packages
chown -R build:build /home/build/packages
# building latest calamares git version
mkdir /home/build/calamares-git
chown -R build:build /home/build/calamares-git
cd /home/build/calamares-git
sudo -u build wget https://raw.githubusercontent.com/endeavouros-team/PKGBUILDS/master/calamares-git/PKGBUILD
sudo -u  build makepkg -f
cp *.pkg.tar.zst /home/build/packages/
rm -R /home/build/calamares-git
echo "###### checking xz version in use ##########"
xz -V
echo "###### checking xz version in use end ##########"
# end building calamares-git
