#!/usr/bin/env bash

echo "### start building calamares git package"
echo "%wheel         ALL = (ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers
pacman -Syu
pacman -S --noconfirm --needed git cmake extra-cmake-modules python-jsonschema python-pyaml python-unidecode gawk qt6-svg qt6-webengine yaml-cpp networkmanager upower kcoreaddons kconfig ki18n kservice kpmcore kwidgetsaddons  squashfs-tools rsync pybind11 cryptsetup doxygen dmidecode gptfdisk hwinfo kparts polkit-qt6 python solid qt6-tools libpwquality ckbcomp qt6-declarative
useradd -m -G wheel -s /bin/bash build
cd /home/build
mkdir -p /home/build/packages
chown -R build:build /home/build/packages
# building latest calamares git version
mkdir /home/build/calamares-git
chown -R build:build /home/build/calamares-git
cd /home/build/calamares-git
sudo -u build wget https://raw.githubusercontent.com/endeavouros-team/PKGBUILDS/master/calamares-git/PKGBUILD
sudo -u  build makepkg -f
echo "---- start list packages  /home/build/calamares-git ----"
ls "/home/build/calamares-git"
echo "---- end list packages  /home/build/calamares-git ----"
cp *.pkg.tar.zst /home/build/packages/
echo "---- start list packages  /home/build/packages/ ----"
ls "/home/build/packages/"
echo "---- end list packages  /home/build/packages/t ----"
cd ..
rm -R /home/build/calamares-git
sudo rm -rf /var/cache/pacman/pkg/*
echo "### end building calamares-git"
