#!/usr/bin/env bash
# clone ISO sources and join the path:
git clone "https://github.com/endeavouros-team/EndeavourOS-ISO.git"

# fetch  package for testing [kpmcore] downgarding to 24.05.2-1 n this case:
#wget -qN --show-progress -P "EndeavourOS-ISO/airootfs/root/packages/" "https://archive.archlinux.org/packages/k/kpmcore/kpmcore-24.05.2-1-x86_64.pkg.tar.zst"

# patch reset.sh to run it for space saving before tarballing later:
patch "EndeavourOS-ISO/reset.sh" < reset.sh.patch

# patch rbs:
patch "EndeavourOS-ISO/run_before_squashfs.sh" < run_before_squashfs.sh.patch

# patch packages:
patch "EndeavourOS-ISO/packages.x86_64" < packages.x86_64.patch

# patch profiledef.sh -- set isoname to unstable:
patch "EndeavourOS-ISO/profiledef.sh" < profiledef.sh.patch

# copy live session Wallpaper and files into ISO structure:
cp livewall.png "EndeavourOS-ISO/airootfs/root/"

# Copy patches to be used inside ISO build process
cp packagechooser.conf.patch "/root/"

# run preperations inside ISO structure
cd EndeavourOS-ISO

# Copy packages from Build Calamares git packages into ISO structure:
cp /home/build/packages/* airootfs/root/packages/

# Get mirrorlist for offline installs
mkdir "airootfs/etc/pacman.d"
wget -qN --show-progress -P "airootfs/etc/pacman.d/" "https://raw.githubusercontent.com/endeavouros-team/EndeavourOS-ISO/main/mirrorlist"

# Get wallpaper for installed system
wget -qN --show-progress -P "airootfs/root/" "https://raw.githubusercontent.com/endeavouros-team/endeavouros-theming/master/backgrounds/endeavouros-wallpaper.png"

# Make sure build scripts are executable
chmod +x "./"{"mkarchiso","run_before_squashfs.sh"}

#get_pkg "eos-settings-plasma"
#pacman -Syw --noconfirm --cachedir "airootfs/root/packages/" eos-settings-plasma
# failing now on autobuilder, it is fetching all dependencies in too. 


chown -R build:build "airootfs/root/endeavouros-skel-liveuser"
cd "airootfs/root/endeavouros-skel-liveuser"
sudo -u build makepkg -f
