#!/usr/bin/env bash
# clone ISO sources and join the path:
git clone "https://github.com/endeavouros-team/EndeavourOS-ISO.git"

patch "EndeavourOS-ISO/run_before_squashfs.sh" < run_before_squashfs.sh.patch

# patch packages:
patch "EndeavourOS-ISO/packages.x86_64" < packages.x86_64.patch

# patch profiledef.sh -- set isoname to unstable:
patch "EndeavourOS-ISO/profiledef.sh" < profiledef.sh.patch

# copy live session Wallpaper and files into ISO structure:
cp livewall.png "EndeavourOS-ISO/airootfs/root/"

# copy testers log helper to liveusers home
cp logsend.sh "EndeavourOS-ISO/airootfs/root/endeavouros-skel-liveuser/src/etc/skel/"
chmod +x "EndeavourOS-ISO/airootfs/root/endeavouros-skel-liveuser/src/etc/skel/logsend.sh"

# Copy packages from Build Calamares git packages into ISO structure:
#cp /home/build/packages/* "EndeavourOS-ISO/airootfs/root/packages/"
#ls "EndeavourOS-ISO/airootfs/root/packages/"

# Get latest calamares devel package
mkdir -p "EndeavourOS-ISO/airootfs/root/packages"
wget -P "EndeavourOS-ISO/airootfs/root/packages/" "https://github.com/endeavouros-team/calamares-devel-package/releases/download/latest/calamares-git-latest-any.pkg.tar.zst"
echo "------> check local packages"
ls "EndeavourOS-ISO/airootfs/root/packages/"

# Get mirrorlist for offline installs
mkdir "EndeavourOS-ISO/airootfs/etc/pacman.d"
wget -P "EndeavourOS-ISO/airootfs/etc/pacman.d/" "https://raw.githubusercontent.com/endeavouros-team/EndeavourOS-ISO/main/mirrorlist"

# Get wallpaper for installed system
wget -P "EndeavourOS-ISO/airootfs/root/" "https://raw.githubusercontent.com/endeavouros-team/Branding/refs/heads/main/backgrounds/endeavouros-wallpaper.png"


# add date to wallpaper
echo "--magick font list--"
magick -list font | grep -i FONT:
echo "--magick font list end--"
magick "EndeavourOS-ISO/airootfs/root/livewall.png" \
  -gravity NorthEast \
  -pointsize 34 \
  -fill white \
  -font "Liberation-Mono" \
  -annotate +10+10 "$(date '+%Y-%m-%d %H:%M:%S')" \
  "EndeavourOS-ISO/airootfs/root/livewall.png"

echo "---check root files start---"
ls "EndeavourOS-ISO/airootfs/root/"
echo "---check root files end---"

# Copy patches to be used inside ISO build process
#cp packagechooser.conf.patch "EndeavourOS-ISO/airootfs/root/"

# run preparations inside ISO structure
cd EndeavourOS-ISO

# Make sure build scripts are executable
chmod +x "./"{"mkarchiso","run_before_squashfs.sh"}

# Build liveuser skel
echo "%wheel         ALL = (ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers
pacman -Syu
# downgrade squashfs-tools [nov 2025] latest version (4.7.3-1) segfaults on image creation
pacman -U https://archive.archlinux.org/packages/s/squashfs-tools/squashfs-tools-4.7.2-1-x86_64.pkg.tar.zst
useradd -m -G wheel -s /bin/bash build
chown -R build:build "airootfs/root/endeavouros-skel-liveuser"
cd "airootfs/root/endeavouros-skel-liveuser"
sudo -u build makepkg -f
