#!/usr/bin/env bash
# clone ISO sources and join the path:
git clone "https://github.com/endeavouros-team/EndeavourOS-ISO.git"

patch "EndeavourOS-ISO/run_before_squashfs.sh" < run_before_squashfs.sh.patch

# patch packages:
patch "EndeavourOS-ISO/packages.x86_64" < packages.x86_64.patch

# patch profiledef.sh -- set isoname to unstable:
patch "EndeavourOS-ISO/profiledef.sh" < profiledef.sh.patch

# copy live session Wallpaper and files into ISO structure:
cp livewall.png "EndeavourOS-ISO/airootfs/root/"


# Copy packages from Build Calamares git packages into ISO structure:
cp /home/build/packages/* "EndeavourOS-ISO/airootfs/root/packages/"
ls "EndeavourOS-ISO/airootfs/root/packages/"

# Get mirrorlist for offline installs
mkdir "airootfs/etc/pacman.d"
wget -qN --show-progress -P "EndeavourOS-ISO/airootfs/etc/pacman.d/" "https://raw.githubusercontent.com/endeavouros-team/EndeavourOS-ISO/main/mirrorlist"

# Get wallpaper for installed system
wget -qN --show-progress -P "EndeavourOS-ISO/airootfs/root/" "https://raw.githubusercontent.com/endeavouros-team/endeavouros-theming/master/backgrounds/endeavouros-wallpaper.png"
echo "---check if files exist under EndeavourOS-ISO/airootfs/root/---"
ls "EndeavourOS-ISO/airootfs/root/"
echo "---check if files exist end---"


# add date to wallpaper

magick "EndeavourOS-ISO/airootfs/root/livewall.png" \
  -gravity NorthEast \
  -pointsize 24 \
  -fill white \
  -font "Noto-Sans" \
  -annotate +10+10 "$(date '+%Y-%m-%d %H:%M:%S')" \
  "EndeavourOS-ISO/airootfs/root/livewall.png"

echo "---check root files start---"
ls "EndeavourOS-ISO/airootfs/root/"
echo "---check root files end---"

# Copy patches to be used inside ISO build process
#cp packagechooser.conf.patch "EndeavourOS-ISO/airootfs/root/"

# run preparations inside ISO structure
cd EndeavourOS-ISO

# Make sure build scripts are executable
chmod +x "./"{"mkarchiso","run_before_squashfs.sh"}

# Build liveuser skel
chown -R build:build "airootfs/root/endeavouros-skel-liveuser"
cd "airootfs/root/endeavouros-skel-liveuser"
sudo -u build makepkg -f
