#!/usr/bin/env bash
# clone ISO sources and join the path:
git clone -b plasma6 https://github.com/endeavouros-team/EndeavourOS-ISO.git

# patch reset.sh to run it for space saving before tarballing later:
patch EndeavourOS-ISO/reset.sh < reset.sh.patch

# patch profiledef.sh -- set isoname to unstable:
patch EndeavourOS-ISO/profiledef.sh < profiledef.sh.plasma6.patch

# patch run_before_squashfs.s to patch clamares before pushing changes:
patch EndeavourOS-ISO/run_before_squashfs.sh < run_before_squashfs.sh.patch
# get calamares patches in:
wget -qN --show-progress -P "EndeavourOS-ISO/airootfs/root/" "https://raw.githubusercontent.com/endeavouros-team/iso-autobuild/main/packagechooser.conf.patch"
wget -qN --show-progress -P "EndeavourOS-ISO/airootfs/root/" "https://github.com/endeavouros-team/iso-autobuild/blob/main/netinstall.yaml.patch"


# copy live session Wallpaper and files into ISO structure:
cp livewall-plasma6.png EndeavourOS-ISO/airootfs/root/livewall.png
cp pacman.conf EndeavourOS-ISO/airootfs/etc/pacman.conf

# run preperations inside ISO structure
cd EndeavourOS-ISO

# Copy packages from Build Calamares git packages into iso structure:
cp /home/build/packages/* airootfs/root/packages/

# Get mirrorlist for offline installs
mkdir "airootfs/etc/pacman.d"
wget -qN --show-progress -P "airootfs/etc/pacman.d/" "https://raw.githubusercontent.com/endeavouros-team/EndeavourOS-ISO/main/mirrorlist"

# Get wallpaper for installed system
wget -qN --show-progress -P "airootfs/root/" "https://raw.githubusercontent.com/endeavouros-team/endeavouros-theming/master/backgrounds/endeavouros-wallpaper.png"


# Make sure build scripts are executable
chmod +x "./"{"mkarchiso","run_before_squashfs.sh"}

# Build liveuser skel
#get_pkg() {
#    pacman -Syw "$1" --noconfirm --cachedir "airootfs/root/packages"
#}

#get_pkg "eos-settings-plasma"

pacman -Syddw --noconfirm --cachedir "airootfs/root/packages" eos-settings-plasma

# current downgrade mesa for calamares lag in vms:
# wget https://archive.archlinux.org/packages/m/mesa/mesa-22.1.7-1-x86_64.pkg.tar.zst
# mv mesa-22.1.7-1-x86_64.pkg.tar.zst "airootfs/root/packages/"

chown -R build:build "airootfs/root/endeavouros-skel-liveuser"
cd "airootfs/root/endeavouros-skel-liveuser"
sudo -u build makepkg -f
