name: Build EndeavourOS devel ISO (plasma6 testing version)

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    permissions:
      contents: write

    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v2
      
      - name: Set current date and hour as environment variable
        run: echo "NOW=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_ENV
                      
      - name: Add EndeavourOS Repo
        run: bash add-EndeavourOS-plasma6
        
      - name: Update packages and install archiso
        run: "pacman -Syu --noconfirm --needed archiso mkinitcpio-archiso git squashfs-tools wget sudo base-devel curl lftp"
        
      - name: create normal user (build) for Build Calamares git packages and prepare actions
        run: bash build-packages
        
      - name: preparations to build ISO
        run: bash prepare-action-plasma6 
        
      - name: Build ISO
        run: bash build-iso

      - name: Add hour to release and tarball
        run: "cp EndeavourOS-ISO/*.log EndeavourOS-ISO/out/ && cd EndeavourOS-ISO/out && tar -czvf EndeavourOS-${{ env.NOW }}-devel-plasma6-iso.tar.gz *.sha512sum *.iso *.log"
        
      - name: Upload a backup to server_DEVEL
        run: "curl -g -k -T EndeavourOS-ISO/out/*.tar.gz -u ${{secrets.SERVER_STRING_DEVEL}}"
